#!/bin/bash

echo "Load for PC 02"
~/551/p2/testing/cpu
echo "Load for PC 03"
ssh o251-03 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 04"
ssh o251-04 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 05"
ssh o251-05 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 06"
ssh o251-06 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 07"
ssh o251-07 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 08"
ssh o251-08 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 09"
ssh o251-09 'bash -s' < ~/551/p2/testing/cpu
echo "Load for PC 10"
ssh o251-10 'bash -s' < ~/551/p2/testing/cpu

