#!/bin/bash

while true; do
  a=$(ssh o251-03 "top -bn1 | grep 'load'")
  b=$(ssh o251-03 "top -bn1 | grep 'a\.out\|PID\|matrix\|mult\|p2'")

  echo $a
  echo $b
  echo -ne "\033[2A"
  sleep 1
done

#echo \*
#  top -bn1 | grep 'a\.out\|PID\|matrix\|mult\|load\|p2'
#echo \*
